FROM dart:stable

# We install unzip and remove the apt-index again to keep the docker image diff small.
RUN apt-get update && apt-get install -y protobuf-compiler && rm -rf /var/lib/apt/lists/*

RUN groupadd --system dart && useradd --no-log-init --system --home /home/dart --create-home -g dart dart

# Work around https://github.com/dart-lang/sdk/issues/47093
RUN find /usr/lib/dart -type d -exec chmod 755 {} \;

USER dart
# Switch to a new, non-root user to use the flutter tool.
# The Flutter tool won't perform its actions when run as root.
COPY --chown=dart:dart dart-pad /home/dart/dart-pad

ENV PATH="/home/dart/.pub-cache/bin:${PATH}"
ENV FLUTTER_CHANNEL="stable"

WORKDIR /home/dart/dart-pad
RUN dart pub get
RUN dart pub global activate grinder
RUN dart pub global activate protoc_plugin

ENTRYPOINT ["grind", "serve", "--host=0.0.0.0", "--port=8000"]


