FROM dart:stable

# We install unzip and remove the apt-index again to keep the docker image diff small.
RUN apt-get update && apt-get install -y wget curl unzip redis-server protobuf-compiler && rm -rf /var/lib/apt/lists/*

RUN groupadd --system dart && useradd --no-log-init --system --home /home/dart --create-home -g dart dart

# Work around https://github.com/dart-lang/sdk/issues/47093
RUN find /usr/lib/dart -type d -exec chmod 755 {} \;

USER dart
# Switch to a new, non-root user to use the flutter tool.
# The Flutter tool won't perform its actions when run as root.
COPY --chown=dart:dart dart-services /home/dart/dart-services
COPY --chown=dart:dart flutter /flutter

ENV PATH="/home/dart/.pub-cache/bin:${PATH}"
ENV FLUTTER_CHANNEL="stable"

WORKDIR /home/dart/dart-services
RUN dart pub get
RUN dart pub global activate grinder
RUN dart pub global activate protoc_plugin

# Set the Flutter SDK up for web compilation.
#RUN dart pub run grinder setup-flutter-sdk
# Build the dill file
RUN dart pub run grinder build-storage-artifacts validate-storage-artifacts

ENTRYPOINT ["./tool/dart_cloud_run.sh", "--port", "${PORT}", "--channel", "stable"]

