name: timu_dart
version: 1.0.0

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  recase: ^4.0.0
  args: ^2.3.0
  flutter_test:
    sdk: flutter
  version: ^2.0.0
  ansicolor: ^2.0.1
  flutter_lints: ^1.0.0
  pub_semver: ^2.1.1
