name: timu_dart
version: 1.0.0

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  cross_file: ^0.3.3+4
  flutter:
    sdk: flutter
  flutter_secure_storage: ^8.0.0
  go_router: ^6.0.10
  google_fonts: ^4.0.3
  http: ^0.13.5
  rxdart: ^0.27.7
  url_launcher: ^6.1.9
  uuid: ^3.0.7
  web_socket_channel: ^2.3.0
  android_content_provider: ^0.3.0
  soundpool: ^2.3.0

dev_dependencies:
  recase: ^4.0.0
  args: ^2.3.0
  flutter_test:
    sdk: flutter
  version: ^2.0.0
  ansicolor: ^2.0.1
  flutter_lints: ^1.0.0
  pub_semver: ^2.1.1
  test: ^1.22.0

flutter:
  assets:
    - lib/assets/
    - lib/assets/app-timu.png

  fonts:
    - family: Timu
      fonts:
        - asset: lib/timu_icons/fonts/Timu.ttf
